### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by keberhardt** [MeasureAuthoringTool/MeasureAuthoringTool_Release#2]
Receiving NoSuchMethodError when attempting to create a measure.

Environment
- Ubuntu 14.04
- Oracle Java SDK java version "1.6.0_45"
- Eclipse Helios
- GWT 2.5.1
- Mozilla Firefox 24.3.0
-MySQL 5.5

I've installed MAT and can sign in, however when I attempt to edit and save a measure (after creating the measure basic with name and type), I receive a 500 error. The console log shows "Service method 'public abstract mat.client.measure.service.SaveMeasureResult mat.client.measure.service.MeasureService.saveMeasureDetails(mat.client.measure.ManageMeasureDetailModel)' threw an unexpected exception: java.lang.NoSuchMethodError: org.apache.xpath.XPathContext.<init>(Z)V" [See full error log message below]

Has anyone else encountered this issue? And tips or ideas on what I might need to change in my configuration?

Thanks for any assistance or pointers you may be able to provide!

- Karen 

10:26:42,188  INFO btpool0-5 server.HibernateStatisticsFilter:47 - Requesting /mat/measureLibrary in session 1982f761qqiwc
10:26:42,198  INFO btpool0-5 server.MeasureLibraryServiceImpl:1856 - In MeasureLibraryServiceImpl.saveMeasureDetails() method..
10:26:42,202  INFO btpool0-5 server.MeasureLibraryServiceImpl:1867 - Saving Measure_Xml
10:26:42,202  INFO btpool0-5 server.MeasureLibraryServiceImpl:790 - In MeasureLibraryServiceImpl.createMeasureDetailsXml()
10:26:42,203  INFO btpool0-5 server.MeasureLibraryServiceImpl:2161 - In MeasureLibraryServiceImpl.setAdditionalAttrsForMeasureXml()
10:26:42,210  INFO btpool0-5 server.MeasureLibraryServiceImpl:2221 - Exiting MeasureLibraryServiceImpl.setAdditionalAttrsForMeasureXml()..
10:26:42,211  INFO btpool0-5 server.MeasureLibraryServiceImpl:792 - creating XML from Measure Details Model
10:26:42,211  INFO btpool0-5 server.MeasureLibraryServiceImpl:863 - In MeasureLibraryServiceImpl.createXml()
10:26:42,219  INFO btpool0-5 mapping.Mapping:282 - Loading mapping descriptors from file:/home/keberhardt/workspace/MeasureAuthoringTool_Release-master/mat/war/WEB-INF/classes/MeasureDetailsModelMapping.xml
10:26:42,391  INFO btpool0-5 server.MeasureLibraryServiceImpl:871 - Marshalling of ManageMeasureDetailsModel is successful..
10:26:42,391  INFO btpool0-5 server.MeasureLibraryServiceImpl:886 - Exiting MeasureLibraryServiceImpl.createXml()
10:26:42,393  INFO btpool0-5 util.XmlProcessor:288 - In XmlProcessor() constructor
10:26:42,395  INFO btpool0-5 util.XmlProcessor:296 - Document Object created successfully for the XML String
   [WARN] Exception while dispatching incoming RPC call
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract mat.client.measure.service.SaveMeasureResult mat.client.measure.service.MeasureService.saveMeasureDetails(mat.client.measure.ManageMeasureDetailModel)' threw an unexpected exception: java.lang.NoSuchMethodError: org.apache.xpath.XPathContext.<init>(Z)V
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:389)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:579)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1097)
	at mat.server.PreventCachingFilter.doFilter(PreventCachingFilter.java:88)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1088)
	at org.springframework.orm.hibernate3.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:198)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1088)
	at mat.server.HibernateStatisticsFilter.doFilter(HibernateStatisticsFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1088)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:343)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:97)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:100)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:78)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:35)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:187)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:79)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:109)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:149)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1088)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:729)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.handler.RequestLogHandler.handle(RequestLogHandler.java:49)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:324)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:505)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:843)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:647)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:380)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:395)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:488)
Caused by: java.lang.NoSuchMethodError: org.apache.xpath.XPathContext.<init>(Z)V
	at org.apache.xpath.jaxp.XPathImpl.eval(XPathImpl.java:207)
	at org.apache.xpath.jaxp.XPathImpl.evaluate(XPathImpl.java:281)
	at mat.server.util.XmlProcessor.checkForScoringType(XmlProcessor.java:585)
	at mat.server.MeasureLibraryServiceImpl.saveMeasureXml(MeasureLibraryServiceImpl.java:1931)
	at mat.server.MeasureLibraryServiceImpl.saveMeasureDetails(MeasureLibraryServiceImpl.java:1868)
	at mat.server.MeasureServiceImpl.saveMeasureDetails(MeasureServiceImpl.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
	... 56 more
[ERROR] 500 - POST /mat/measureLibrary (127.0.0.1) 57 bytes
   Request headers
      Host: 127.0.0.1:8888
      User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:24.0) Gecko/20100101 Firefox/24.0
      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
      Accept-Language: en-US,en;q=0.5
      Accept-Encoding: gzip, deflate
      Cookie: __utma=96992031.1051938367.1419014988.1419594631.1419601423.10; __utmz=96992031.1419014988.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmb=96992031.25.10.1419601423; __utmc=96992031; __utmt=1; JSESSIONID=1982f761qqiwc
      Connection: keep-alive
      Referer: http://127.0.0.1:8888/Mat.html?gwt.codesvr=127.0.0.1%3A9997
      X-GWT-Permutation: HostedMode
      X-GWT-Module-Base: http://127.0.0.1:8888/mat/
      Content-Type: text/x-gwt-rpc; charset=utf-8
      Content-Length: 633
      Pragma: no-cache
      Cache-Control: no-cache
   Response headers
      Content-Type: text/plain

**Comment by keberhardt** [comment]
This was caused by a conflicting jar file. Removing xalan-2.6.0.jar from /MeasureAuthoringTool_Release-master/mat/war/WEB-INF/lib resolved the issue.
